CREATE STREAM PRE_LEADS WITH (kafka_topic='postgres.public.pre_leads', value_format='AVRO');
CREATE STREAM CLEAN_LEADS WITH (kafka_topic='clean_leads', value_format='AVRO') AS SELECT AFTER->USER_ID, AFTER->FIRST_NAME, AFTER->LAST_NAME, AFTER->COMPANY, AFTER->EMAIL_ADDRESS, AFTER->PHONE_NUMBER FROM PRE_LEADS WHERE OP='c';
